### ISSUE TITLE
it doesn't work on PHP 7.3 

### ISSUE THREAD

**Issue by ghost** [clagiordano/weblibs-configmanager#1]
hello everybody 
i'm trying to use this library to my project on PHP 7.3 & Apache2.
but when attend to  execute this ligne code ''$config = new ConfigManager("configfile.php");' 

nothing is appearing : error , warning,...

**Comment by clagiordano** [comment]
Hi @myaset,

I'm actually using this library on production environment with php7.3 and php-fpm+nginx 
but I have not found any error on that environment.

Which version are you using?
could you please check on your php.ini config file if the following settings are enabled?

- error_reporting
```error_reporting = E_ALL```
- display_errors
```display_errors = On```
- display_startup_errors
```display_startup_errors = On```

Can you also provide a snippet of code to reproduce this issue?

Thanks.

**Comment by ghost** [comment]
Hi @clagiordano, 

It works perfectly, it's because of autoloader  from my code.

 Thank you
